#!/usr/bin/env bash
# Runs git blame on all tracked source files and reports line-count percentage per contributor.

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"

EXTENSIONS="dart|swift|kt|java|py|sh|yaml|yml|json|xml|gradle|toml"

# Flutter platform boilerplate to exclude (generated by `flutter create`, not authored code).
# Custom native bridges (CloudKitSyncBridge.swift, MusicKitBridge.swift) are kept.
BOILERPLATE_DIRS="^(android|linux|windows|web)/"
BOILERPLATE_IOS="^ios/(Runner/(AppDelegate|Assets\.xcassets)|RunnerTests)/"
BOILERPLATE_MACOS="^macos/(Runner/(AppDelegate|MainFlutterWindow)|RunnerTests)/"
# Raw tune data (JSON collections + license texts) and bundled third-party JS library
DATA_SOURCES="^assets/(data/|abcjs/)"
# One-time scraper scripts that generate assets/data/*.json — never compiled into the app
SCRAPE_SCRIPTS="^lib/remote_tune_sources/[^/]+_scrape\.dart$"
# Drift-generated artifacts: migration steps, schema snapshots (JSON + Dart)
DRIFT_GENERATED="(database\.steps\.dart|drift_schema.*\.json|test/drift/.*/generated/)"

git -C "$REPO_ROOT" ls-files \
  | grep -E "\.($EXTENSIONS)$" \
  | grep -v -E "\.(g|freezed)\.dart$" \
  | grep -v "pubspec\.lock" \
  | grep -v -E "$BOILERPLATE_DIRS" \
  | grep -v -E "$BOILERPLATE_IOS" \
  | grep -v -E "$BOILERPLATE_MACOS" \
  | grep -v -E "$DATA_SOURCES" \
  | grep -v -E "$SCRAPE_SCRIPTS" \
  | grep -v -E "$DRIFT_GENERATED" \
  | while IFS= read -r file; do
      git -C "$REPO_ROOT" blame --line-porcelain "$file" 2>/dev/null \
        | grep "^author " \
        | sed 's/^author //'
    done \
  | sort \
  | uniq -c \
  | sort -rn \
  | awk '
      BEGIN { total = 0 }
      { total += $1; lines[NR] = $1; names[NR] = ""; for (i=2;i<=NF;i++) names[NR] = names[NR] (i>2?" ":"") $i; count = NR }
      END {
        print "Git blame attribution (" total " total lines)"
        print "============================================"
        for (i = 1; i <= count; i++)
          printf "%6.2f%%  %-6d  %s\n", lines[i]/total*100, lines[i], names[i]
      }'
