#!/usr/bin/env bash
# Runs git blame on all tracked source files and reports line-count percentage per contributor.

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"

EXTENSIONS="dart|swift|kt|java|py|sh|yaml|yml|json|xml|gradle|toml"

# Flutter platform boilerplate to exclude (generated by `flutter create`, not authored code).
# Custom native bridges (CloudKitSyncBridge.swift, MusicKitBridge.swift) are kept.
BOILERPLATE_DIRS="^(android|linux|windows|web)/"
BOILERPLATE_IOS="^ios/(Runner/(AppDelegate|Assets\.xcassets)|RunnerTests)/"
BOILERPLATE_MACOS="^macos/(Runner/(AppDelegate|MainFlutterWindow)|RunnerTests)/"
# Raw tune data (JSON collections + license texts) and bundled third-party JS library
DATA_SOURCES="^assets/(data/|abcjs/)"
# One-time scraper scripts that generate assets/data/*.json — never compiled into the app
SCRAPE_SCRIPTS="^lib/remote_tune_sources/[^/]+_scrape\.dart$"
# Drift-generated artifacts: migration steps, schema snapshots (JSON + Dart)
DRIFT_GENERATED="(database\.steps\.dart|drift_schema.*\.json|test/drift/.*/generated/)"
# Hand-written DB migration scaffolding (migration tests). Not feature IP — boilerplate
# that verifies schema upgrades, regenerated/extended every schema bump.
MIGRATION_CODE="(^test/drift/|migration_test\.dart$)"

git -C "$REPO_ROOT" ls-files \
  | grep -E "\.($EXTENSIONS)$" \
  | grep -v -E "\.(g|freezed)\.dart$" \
  | grep -v "pubspec\.lock" \
  | grep -v -E "$BOILERPLATE_DIRS" \
  | grep -v -E "$BOILERPLATE_IOS" \
  | grep -v -E "$BOILERPLATE_MACOS" \
  | grep -v -E "$DATA_SOURCES" \
  | grep -v -E "$SCRAPE_SCRIPTS" \
  | grep -v -E "$DRIFT_GENERATED" \
  | grep -v -E "$MIGRATION_CODE" \
  | while IFS= read -r file; do
      git -C "$REPO_ROOT" blame --line-porcelain "$file" 2>/dev/null \
        | grep "^author " \
        | sed 's/^author //'
    done \
  | tr -s ' ' \
  | sort | uniq -c | sort -rn \
  > /tmp/stats_lines.txt

git -C "$REPO_ROOT" log --format="%an" \
  | tr -s ' ' \
  | sort | uniq -c | sort -rn \
  > /tmp/stats_commits.txt

awk '
  FNR == NR {
    count = $1
    name = ""
    for (i = 2; i <= NF; i++) name = name (i > 2 ? " " : "") $i
    lines[name] = count
    order[++n] = name
    line_total += count
    next
  }
  {
    count = $1
    name = ""
    for (i = 2; i <= NF; i++) name = name (i > 2 ? " " : "") $i
    commits[name] = count
    commit_total += count
    if (!(name in lines)) { lines[name] = 0; order[++n] = name }
  }
  END {
    printf "\n%-22s  %7s  %6s    %7s  %8s\n", "Contributor", "Lines", "Lines%", "Commits", "Commits%"
    printf "%-22s  %7s  %6s    %7s  %8s\n", "----------------------", "-------", "------", "-------", "--------"
    for (i = 1; i <= n; i++) {
      name = order[i]
      lc = lines[name] + 0
      cc = commits[name] + 0
      lpct = line_total > 0 ? lc / line_total * 100 : 0
      cpct = commit_total > 0 ? cc / commit_total * 100 : 0
      printf "%-22s  %7d  %5.1f%%    %7d  %7.1f%%\n", name, lc, lpct, cc, cpct
    }
    printf "\n%-22s  %7d  %6s    %7d  %8s\n", "TOTAL", line_total, "100%", commit_total, "100%"
  }
' /tmp/stats_lines.txt /tmp/stats_commits.txt
